name: Android Test Build

on:
  pull_request:
    branches: [ dev, master, 'milestone/**' ]
  workflow_dispatch:
    branches: [ dev, master, 'milestone/**' ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
      
    - name: set up JDK 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
        
    - name: Build all artifacts
      run: ./gradlew assembleRelease
