  
name: Android Release Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:
    branches: [ dev ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.2
      
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
        
    - name: Build all artifacts
      run: ./gradlew bundleRelease
      
    - name: Upload
      uses: actions/upload-artifact@v2.2.2
      with:
        name: appBundle
        path: app/build/outputs/bundle/withoutFileLogsRelease/app-withoutFileLogs-release.aab
