name: Android Test Build

on:
  pull_request:
    branches: [ dev, master, 'milestone/**' ]
  workflow_dispatch:
    branches: [ dev, master, 'milestone/**' ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.4.0
      
    - name: set up JDK 11
      uses: actions/setup-java@v3.10.0
      with:
        distribution: 'corretto'
        java-version: 11
        
    - name: Build all artifacts
      run: ./gradlew assembleRelease
