name: Android Release Build
on:
  push:
    branches: [ master, dev, 'milestone/**' ]
  workflow_dispatch:
    branches: [ master, dev, 'milestone/**' ]
       
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.4.0
      
    - name: set up JDK 11
      uses: actions/setup-java@v3.10.0
      with:
        distribution: 'corretto'
        java-version: 11
        
    - name: Build bundle
      run: ./gradlew bundleRelease
      
    - name: Build APK
      run: ./gradlew assembleRelease
      
    - name: Sign test APK
      id: sign_test_apk
      uses: ilharp/sign-android-release@v1
      with:
        # The directory to find your release to sign
        releaseDir: app/build/outputs/apk/withFileLogs/release
        signingKey: ${{ secrets.SIGNING_KEY }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        
    - name: Sign release APK
      id: sign_apk
      uses: ilharp/sign-android-release@v1
      with:
        # The directory to find your release to sign
        releaseDir: app/build/outputs/apk/withoutFileLogs/release
        signingKey: ${{ secrets.SIGNING_KEY }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        
        
    - name: Sign bundle
      id: sign_bundle
      uses: ilharp/sign-android-release@v1
      with:
        # The directory to find your release to sign
        releaseDir: app/build/outputs/bundle/withoutFileLogsRelease/
        signingKey: ${{ secrets.SIGNING_KEY }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload test APK
      uses: actions/upload-artifact@v3.1.2
      with:
        name: withFilelogsTestApk
        path: ${{steps.sign_test_apk.outputs.signedReleaseFile}}
        
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.2
      with:
        name: releaseAPK
        path: ${{steps.sign_apk.outputs.signedReleaseFile}}
      
    - name: Upload bundle
      uses: actions/upload-artifact@v3.1.2
      with:
        name: appBundle
        path: ${{steps.sign_bundle.outputs.signedReleaseFile}}
