name: Android Release Bundle Build
on:
  push:
    branches: [ master, dev, 'milestone/**' ]
  workflow_dispatch:
    branches: [ master, dev, 'milestone/**' ]
       
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.4.0
      
    - name: set up JDK 17
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'corretto'
        java-version: 17
        
    - name: Build bundle
      run: ./gradlew bundleRelease
      
        
    - name: Sign bundle
      id: sign_bundle
      uses: ilharp/sign-android-release@v1
      with:
        # The directory to find your release to sign
        releaseDir: app/build/outputs/bundle/withoutFileLogsRelease/
        signingKey: ${{ secrets.SIGNING_KEY }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
     
    - name: Upload bundle
      uses: actions/upload-artifact@v3.1.2
      with:
        name: appBundle
        path: ${{steps.sign_bundle.outputs.signedFile}}
